channels:
  - conda-forge
dependencies:
  - python=3.9
  - cartopy
  - datashader
  - erddapy
  - fsspec
  - geoviews
  - hvplot
  - jupyter-panel-proxy
  - joblib
  - intake
  - intake-xarray
  - ipyleaflet
  - metpy
  - nbgitpuller
  - pandas
  - requests
  - seawater
  - tqdm
  - xarray
  - zarr
